# Generated by Django 5.2.5 on 2025-08-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='repassword',
        ),
    ]
